version: 0.1.{build}
image:
- Visual Studio 2017
- Ubuntu

build:
  verbosity: minimal

branches:
  except:
  - gh-pages

init:
- git config --global core.autocrlf input

build_script:
- ps: $env:NUGET_PACKAGES = "$env:APPVEYOR_BUILD_FOLDER\.nuget"
- ps: .\build.cmd -t pack -c Release -v "$env:APPVEYOR_BUILD_VERSION" /p:GhPages=true
- sh: export NUGET_PACKAGES="$APPVEYOR_BUILD_FOLDER/.nuget"
- sh: ./build.sh -t pack -c Release -v "$APPVEYOR_BUILD_VERSION" /p:GhPages=true

test_script:
- ps: .\build.cmd -s -t test -c Release --push-tests "https://ci.appveyor.com/api/testresults/mstest/$env:APPVEYOR_JOB_ID"
- sh: ./build.sh -s -t test -c Release --push-tests "https://ci.appveyor.com/api/testresults/mstest/$APPVEYOR_JOB_ID"

environment:
  APPVEYOR_YML_DISABLE_PS_LINUX: true
  GH_TOKEN:
    secure: dhFy1eZoqG4QPkKTuLFxix7QQMxaIyIpYjkvTU3CukYZz1CEOJeHfBSaT8tkPsGL

nuget:
  disable_publish_on_pr: true

cache:
- .nuget

for:

# Publish to NuGet and github.io only from Windows on master
- branches:
    only:
    - master
  matrix:
    only:
    - image: Visual Studio 2017
  artifacts:
  - path: build\*.nupkg
    name: nuget
  on_success:
  - ps: .\tools\gh-pages.ps1 -env appveyor
