version: 0.1.{build}
image: Visual Studio 2017

build:
  verbosity: minimal

branches:
  except:
  - gh-pages

init:
- git config --global core.autocrlf input

build_script:
- ps: .\build.cmd -t pack -c Release -v "$env:APPVEYOR_BUILD_VERSION" /p:GhPages=true

test_script:
- ps: .\build.cmd -s -t test -c Release --push-tests "https://ci.appveyor.com/api/testresults/mstest/$env:APPVEYOR_JOB_ID"

on_success:
- ps: .\tools\gh-pages.ps1 -env appveyor

environment:
  GH_TOKEN:
    secure: dhFy1eZoqG4QPkKTuLFxix7QQMxaIyIpYjkvTU3CukYZz1CEOJeHfBSaT8tkPsGL

for:
- branches:
    only:
    - master
  artifacts:
  - path: build\*.nupkg
    name: nuget
